"""Alembic migration: add avatar_url, is_admin to users; create notification, password_reset_token, support_requests tables"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg

# revision identifiers, used by Alembic.
revision = '20260521021500'
 down_revision = 'a3f52fb2dea2_initial_v3_topology'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust ###
    # Add columns to users
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # Create notification table
    op.create_table(
        'notification',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('user_id', pg.UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('title', sa.String, nullable=False),
        sa.Column('message', sa.Text, nullable=False),
        sa.Column('is_read', sa.Boolean, default=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    # Create password_reset_tokens table
    op.create_table(
        'password_reset_tokens',
        sa.Column('id', pg.UUID(as_uuid=True), primary_key=True, default=sa.text('uuid_generate_v4()')),
        sa.Column('user_id', pg.UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('token', sa.String, unique=True, nullable=False, index=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('used', sa.Boolean, default=False, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    # Create support_requests table
    op.create_table(
        'support_requests',
        sa.Column('id', pg.UUID(as_uuid=True), primary_key=True, default=sa.text('uuid_generate_v4()')),
        sa.Column('user_id', pg.UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('subject', sa.String, nullable=False),
        sa.Column('message', sa.Text, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_table('support_requests')
    op.drop_table('password_reset_tokens')
    op.drop_table('notification')
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('avatar_url')
    # ### end Alembic commands ###
